# Generated by Django 5.1.3 on 2024-11-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_managerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerrequest',
            name='updated_at',
        ),
    ]
