# Generated by Django 5.1.3 on 2024-11-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_emails', to='authenticate.course')),
            ],
        ),
    ]
