# Generated by Django 5.1.3 on 2024-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
