# Generated by Django 5.1.3 on 2024-12-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_remove_notification_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
