# Generated by Django 5.1.3 on 2024-12-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
