# Generated by Django 5.1.3 on 2024-12-16 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_module_is_completed_delete_usermodulecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='users_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
